// change this if you want to change the default list of topics
var topics = {
	'Agile'   : [
		"Agile Tools",
		"Agile",
		"Automated Testing",
		"Baby Boomers vs Millenials",
		"Build quality in",
		"Burndown Charts",
		"Cat People",
		"Continuous Delivery",
		"Continuous Improvement",
		"Daily Stand-up",
		"Discovery",
		"Don't try this at home",
		"Door to door sales",
		"Empowerment",
		"Failure",
		"Guilds, Tribes and Squads",
		"Happy Marriages",
		"Heavy Metal",
		"Hopes and Fears",
		"If you were born 100 years ago",
		"Leadership",
		"Lean Startup",
		"Living the 'Dream'",
		"My worst agile experience",
		"#noestimates",
		"#noprojects",
		"Pair Programming",
		"Planning ",
		"Planning Poker",
		"Presentation Karaoke",
		"Product Ownership",
		"Project Managers",
		"Retrospective",
		"Road Trip",
		"Scaling Agile",
		"Scrum Masters",
		"Scrum",
		"SDLC",
		"Spending time with your family",
		"Star Trek",
		"Star Wars",
		"Success",
		"Teams",
		"Technology",
		"Test-Driven Development",
		"Testing",
		"The calm before the storm",
		"The last book you read",
		"This presentation",
		"Too much feedback",
		"Traffic in this city",
		"Training",
		"Velocity",
		"What it takes to be a Scrum Master",
		"Your boss",
		"Your company",
		"Your dream job",
		"Your favorite pet",
		"Your favourite movie",
		"Your ideal relaxing day",
		"Your last holiday",
		"Your weekend",
		"Zeppelins and Airships",
	],
	'Business': [
		'Add your own topics',
		'One per line',
	],
	'Freeform': [
		'Add your own topics',
		'One per line',
	]
};
