// change this if you want to change the default list of topics
var topics = {
	'Delex 2019' : [
		"Avaliablility 99.9999999",
		"Testing framework architecture",
		"Can not reproduce",
		"Mono repository",
		"DevOooooooooooppppsss",
		"Your company",
		"Testing in production",
		"Cloud Technology",
		"Serverless",
		"AWS",
		"Not in the scope",
		"Night before release",
		"Jenkins",
		"Chaos testing",
		"Kobol",
		"Silver bullet",
		"IT Antihype",
		"Building on workstation",
		"Test-Driven Development",
		"xUnit",
		"Yesterday it worked",
		"Mobile testing",
		"Shit and stick",
		"<INSERT TOPIC HERE>",
		"Data Science",
		"Not invented here",
		"Funny cats in server room",
		"Agile coaching in siberian metal factory",
		"Automated Testing",
		"NoSQL vs SQL",
		"Open source"
	]
};
